### ISSUE TITLE
Still broken

### ISSUE THREAD

**Issue by Farcus2000** [PooledEnergy/PooledEnergyApp#1]
Equipment status does not update.

schedule does not work does not display

**Comment by johndpope** [comment]
What happens if you press refresh?

**Comment by pe-johndpope** [comment]
Hi Farcus,

Thanks for the feedback.
There's a timer of 30 seconds to poll system for status of equipment. 
It's possible you have an out of date cached version when you start up - if you wait on homescreen long enough - if will refresh. We're looking to optimise this - and the schedule is being worked on - expect a 7.80 release soon.

Apologies for any inconvenience.

**Comment by pe-johndpope** [comment]
We're currently testing on Apple testflight / android beta - 7.81
Feel free to grab this - still a few kinks we're updating. 
links in the readme - 
https://github.com/PooledEnergy/PooledEnergyApp

**Comment by pe-johndpope** [comment]
Did the latest 7.86 resolve things ? let me know either way. I'll close for now.

**Comment by Farcus2000** [comment]
No. Exactly the same. 
    	Get Outlook for iOS
    
  

 From: JP ***@***.***>Sent: Tuesday, May 17, 2022 10:57 amTo: PooledEnergy/PooledEnergyApp ***@***.***>Cc: Farcus2000 ***@***.***>; Author ***@***.***>Subject: Re: [PooledEnergy/PooledEnergyApp] Still broken (Issue #1) 
Did the latest 7.86 resolve things ? let me know either way I'll close for now.

**Comment by Farcus2000** [comment]
There is a scheduled run of the pool heating which has not activated today.
    	Get Outlook for iOS
    
  

 From: JP ***@***.***>Sent: Tuesday, May 17, 2022 10:57 amTo: PooledEnergy/PooledEnergyApp ***@***.***>Cc: Farcus2000 ***@***.***>; Author ***@***.***>Subject: Re: [PooledEnergy/PooledEnergyApp] Still broken (Issue #1) 
Did the latest 7.86 resolve things ? let me know either way I'll close for now.

**Comment by pe-johndpope** [comment]
Hi Farcus,
I did a quick search on backend for your account - could you please email info@pooledenergy.com.au - we will formally track this and help troubleshoot. There's a few moving parts here - and it's possible your controller may not be responsive.
